# Ngay khi sự kiện phát sinh
# Lập tức kích hoạt workflow này
on:
  push:
  pull_request:
  workflow_dispatch:
  runs-on: ubuntu-latest

# job Test
test:
steps:
  # B1: Lấy source về
  - name: Clone/Checkout source code
    uses: actions/checkout@v6
  # B2: Cài đặt các thư viện phụ thuộc
  - name: Install dependencies
    run: |
      node --version
      npm --version
      pwd
      ls -la
  # B3: run tests
  - name: Run tests
    run: npm test
